DEV-2791: update attributes through API
realvnc-labs/rport pull request #1012
Opened 2023-04-13 20:42 UTC by KonradKuznicki

DEV-2791: update attributes through API

2023-04-14 17:33 UTC, domenipavec requested changes

2023-04-14 17:33 UTC, domenipavec commented on api-doc/openapi/paths/clients_{client_id}_attributes.yaml
> +      '*/*':
All `*/*` in this file should be `application/json`.

2023-04-14 17:33 UTC, domenipavec commented on server/api_handler_client_attributes.go
> +	al.writeJSONResponse(w, http.StatusOK, api.NewSuccessPayload("ok"))
This is different from all other endpoints, where we return `StatusNoContent` if there's no actual data.

2023-04-14 17:33 UTC, domenipavec commented on bdd/client_attributes/update/e2e_test.go
> +	}
I think these should be part of the `StartClientAndServerAndWaitForConnection`, since it has `Wait` in a name I don't think it makes sense to have to then wait 100ms manually.

2023-04-14 17:33 UTC, domenipavec commented on bdd/helpers/goRunner.go
> +func StartClientAndServerAndWaitForConnection(ctx context.Context, t *testing.T, projectRoot string) (*exec.Cmd, *exec.Cmd) {
Nit.: You could find project root by traversing up until you find `go.mod` file, then it wouldn't have to be specified manually.

2023-04-14 17:33 UTC, domenipavec commented on client/client.go
> +			c.Logger.Infof("received request to update attributes")
I don't think it makes sense to log this differently then other requests. There's a generic request type log above, if you think it should be on info level, change the level of that.

2023-04-14 17:33 UTC, domenipavec commented on client/client.go
> +	data, err := json.Marshal(configHolder)
Huh, why not just use payload directly?

2023-04-14 17:33 UTC, domenipavec commented on client/client.go
> +	}{Status: "OK"}, nil
I don't think you should invent response that's always the same. Just keep the response `nil`, which means ok if there's no error.

2023-04-14 17:33 UTC, domenipavec commented on docs/content/advanced/no11-attributes.md
> +2. As a separate file on the client `attributes file`
Is `attributes_file` different from `attributes_file_path` or should this be changed?

2023-04-14 17:33 UTC, domenipavec commented on docs/content/advanced/no11-attributes.md
> +3. Through the API - `attributes file` has to be enabled
I'm not sure what `has to be enabled` means. Is there a separate `enable` flag, or should this be `has to be set`?

2023-04-14 17:33 UTC, domenipavec commented on client/client.go
> +	"github.com/realvnc-labs/rport/server/clients"
I don't think we should be importing `server` package from client. By our current code organization, the shared code should live in `share`.

2023-04-14 17:33 UTC, domenipavec commented on server/clients/client.go
> +	copierClientsToAttrs(*c, &attr) //nolint:govet
Is the copy really neccessary, wouldn't it work if you use struct embedding to add `Attributes` to `Client`?

2023-04-14 17:33 UTC, domenipavec commented on server/clients/client.go
> +	pairs := []dyncopy.FromToPair{dyncopy.NewPair("Tags", "Tags"), dyncopy.NewPair("Labels", "Labels")}
Is all this reflection and complicated code really necessary for 2 fields? Just make a hard coded copy function.

2023-04-18 09:17 UTC, morestatic commented
are you seeing double comments? ... if so, not sure why that's happening. i didn't submit twice.

2023-04-19 13:29 UTC, KonradKuznicki commented on server/api_handler_client_attributes.go
> +	al.writeJSONResponse(w, http.StatusOK, api.NewSuccessPayload("ok"))
I thought about it but, there is a situation (line 92) when there is more information sent.
But on a second thought, it would more clearly indicate the difference between line 92 and 95

2023-04-19 13:31 UTC, KonradKuznicki commented on docs/content/advanced/no11-attributes.md
> +2. As a separate file on the client `attributes file`
Yes, it is different, because we don't expect this "attributes_file" to exist even when "attributes_file_path" is set

2023-04-19 13:34 UTC, KonradKuznicki commented on docs/content/advanced/no11-attributes.md
> +3. Through the API - `attributes file` has to be enabled
it is better explained here https://github.com/realvnc-labs/rport/pull/1012/files/b485ba0b3997fd9a2a70fabe78e584ee445adaf9#diff-825eafc99c3bb12795f2864caffa7943c13f99f7c5d17e55a3669dca4ac8ed62R91

2023-04-19 13:45 UTC, KonradKuznicki commented on server/clients/client.go
> +	pairs := []dyncopy.FromToPair{dyncopy.NewPair("Tags", "Tags"), dyncopy.NewPair("Labels", "Labels")}
@morestatic you are exactly right, I did it to start a discussion but it just so happens that after yesterday there is a ticket. Not for the full refactor (I have to confirm that with Thorsten) though at least for the client 
https://tracker.rport.io/issue/DEV-2841/Speed-up-client-search
after some hacking, I've got 50x improvement using reflection and struct coping,
from ~2.2s to ~40ms

2023-04-19 13:46 UTC, KonradKuznicki commented on server/clients/client.go
> +	copierClientsToAttrs(*c, &attr) //nolint:govet
@domenipavec That was my first approach, yet it would generate an enormous amount of refactoring 
which I think is necessary for multiple reasons

2023-04-19 14:25 UTC, domenipavec commented on server/api_handler_client_attributes.go
> +	al.writeJSONResponse(w, http.StatusOK, api.NewSuccessPayload("ok"))
@KonradKuznicki That's weird that you're returning status ok on line 92 for an error. I think it would be better to return `StatusNoContent` here and an error on line 92.

2023-04-21 11:20 UTC, morestatic commented on server/clients/client.go
> +	pairs := []dyncopy.FromToPair{dyncopy.NewPair("Tags", "Tags"), dyncopy.NewPair("Labels", "Labels")}
i think i'm with @domenipavec on this one. keep the fancy copy for the big structs and then keep this copy as simple as it can be.

2023-04-24 11:21 UTC, KonradKuznicki commented on client/client.go
> +	"github.com/realvnc-labs/rport/server/clients"
I agree it is ugly. I find this structure unfortunate. 
Moving just attributes to share feels wrong but moving the entire client representation feels wrong as well.
Serious refactoring sound appropriate though not in scope for this ticket.
So only code duplication seems wright but well... you somehow have to be sure you have the same structure on both ends - ugly and error-prone as well.
I think that the current solution is ugly but not error-prone.
but @morestatic @domenipavec feel free to vote

2023-04-24 11:24 UTC, KonradKuznicki commented on server/api_handler_client_attributes.go
> +	if req.ContentLength > 2^10*5 { // limit JSON to 5KB
to be honest it should probably be a configuration on the endpoint though - I'll research that

2023-04-24 11:24 UTC, KonradKuznicki commented on server/api_handler_client_attributes.go
> +	al.writeJSONResponse(w, http.StatusOK, api.NewSuccessPayload("ok"))
@domenipavec It's something between error and success because when the client will reconnect the database will be updated. I've talked with Thorsten about it and in this scenario, we are ok with "eventual consistency".

2023-04-24 14:24 UTC, KonradKuznicki commented on client/client.go
> +	data, err := json.Marshal(configHolder)
I think that saving stuff on the client is quite risky (from various perspectives), this way I'm ensuring that whatever is saved should be at least readable by the client without error. 

After reading this comment and thinking deeper about the problem we should have better feature negotiation between the client and server 
because newer versions of the server might want to set up things that would be silently dismissed by the client.
Not to mention other failure modes.

Though  this would be a much bigger refactoring than this ticket

2023-04-24 14:33 UTC, KonradKuznicki commented on client/client.go
> +	}{Status: "OK"}, nil
I agree that nil would be enough now.
Though :
- it feels weird to return nil on the success - the rest of the code expects "something"
- it's sort of against the way Go is designed
- its harder when debugging to tell that everything is correct

But if you insist I can make it nil

2023-04-24 14:56 UTC, KonradKuznicki commented on client/client.go
> +	data, err := json.Marshal(configHolder)
https://tracker.rport.io/issue/DEV-2859/Feature-version-negotiation-between-client-and-server
I've created a ticket for that

2023-04-24 22:09 UTC, KonradKuznicki commented on server/clients/client.go
> +	pairs := []dyncopy.FromToPair{dyncopy.NewPair("Tags", "Tags"), dyncopy.NewPair("Labels", "Labels")}
removed for further discussion
https://tracker.rport.io/issue/DEV-2860/refactor-manual-property-copying-between-structs

2023-04-24 22:36 UTC, KonradKuznicki commented on server/api_handler_client_attributes.go
> +func (al *APIListener) withActiveClient(next http.Handler) http.Handler {
https://tracker.rport.io/newIssue?draftId=92-6829

2023-04-25 16:35 UTC, domenipavec commented on client/client.go
> +	}{Status: "OK"}, nil
I'm fine if you leave it like this, just seems a bit weird to have this hardcoded.

2023-04-25 16:44 UTC, domenipavec commented on client/client.go
> +	"github.com/realvnc-labs/rport/server/clients"
I think ideally all structs for server-client communication should be separate from structs we use for storing data on either client or server and stored in `share`. I'm ok if you want to leave it like this, but I think it might set a dangerous precedent for high coupling of server and client data structs.

2023-04-25 16:44 UTC, domenipavec commented on server/clients/client.go
> +	pairs := []dyncopy.FromToPair{dyncopy.NewPair("Tags", "Tags"), dyncopy.NewPair("Labels", "Labels")}
@KonradKuznicki Please also remove `dyncopy` from the codebase for now.

2023-04-25 16:46 UTC, domenipavec commented on server/api_handler_client_attributes.go
> +	if req.ContentLength > 2^10*5 { // limit JSON to 5KB
@KonradKuznicki We already have a general `max_request_bytes` (default 10KB) for all endpoints. Do we really need a specific limit and setting for this endpoint?

2023-04-25 20:39 UTC, KonradKuznicki commented on server/clients/client.go
> +	pairs := []dyncopy.FromToPair{dyncopy.NewPair("Tags", "Tags"), dyncopy.NewPair("Labels", "Labels")}
done

2023-04-26 10:55 UTC, KonradKuznicki commented on server/api_handler_client_attributes.go
> +func (al *APIListener) withActiveClient(next http.Handler) http.Handler {
https://tracker.rport.io/issue/DEV-2861/Replace-copy-paste-client-validation-with-client-in-context

2023-04-26 11:32 UTC, KonradKuznicki commented on server/api_handler_client_attributes.go
> +	if req.ContentLength > 2^10*5 { // limit JSON to 5KB
I removed the limitation

2023-04-26 16:02 UTC, KonradKuznicki commented on client/client.go
> +	"github.com/realvnc-labs/rport/server/clients"
its' moved to shared/model/attributes

2023-04-26 17:28 UTC, domenipavec approved these changes

2023-04-27 01:09 UTC, morestatic approved these changes

2023-04-27 08:33 UTC, merged