dev-2961 notification service
realvnc-labs/rport pull request #1135
Opened 2023-06-28 09:51 UTC by KonradKuznicki

2023-06-29 04:34 UTC, morestatic requested changes
@KonradKuznicki I think we should have a call as soon as you're available this morning. nothing too critical but we need to clarify the use of the `refs` package, cause it has crept into the database structure. i did find some clearer examples in the tests and it might be ok and invalidate some of my comments here, but we should confirm before merging into master.

most of the rest of the comments are relatively minor but should probably be applied.

noticed that you added another wip commit (for filtering). this now effectively blocks any master merge until the wip is completed. probably would have been better to do the new work on a separate branch, but the commit has been made, so we'll need to complete the work now.

2023-06-29 04:34 UTC, morestatic commented on server/notifications/api.go
> +type REST interface {
is this used anywhere?

2023-06-29 04:34 UTC, morestatic commented on server/notifications/api_test.go
> +package notifications
should this file be deleted? or is there more to come?

2023-06-29 04:34 UTC, morestatic commented on server/notifications/consumer_test.go
> +package notifications
should this file be deleted? or is there more to come?

2023-06-29 04:34 UTC, morestatic commented on server/notifications/runner.go
> +package notifications
is this file best called `processor.go`, rather than `runner.go`? it all seems to be about `processor`.

2023-06-29 04:34 UTC, morestatic commented on server/notifications/runner_test.go
> +func (suite *ProcessorTestSuite) SendUnknown() notifications.NotificationDetails {
a comment might be handy here? i'm not really understanding why called `SendUnknown`?

2023-06-29 10:00 UTC, KonradKuznicki commented
- [ ] drop origin - use identifiable instead
- [ ] identifiable consists of meta and id with ::: separator
- [ ] drop filtering - fix list

2023-06-29 21:42 UTC, KonradKuznicki commented on server/api_listener.go
> +	me "github.com/realvnc-labs/rport/server/notifications/repository/sqlite"
done

2023-06-29 21:42 UTC, KonradKuznicki commented on server/api_listener.go
> +	logger2 "github.com/realvnc-labs/rport/server/notifications/channels/logger"
done

2023-06-29 21:42 UTC, KonradKuznicki commented on server/api_listener.go
> +	mu                     sync.RWMutex
done

2023-06-29 21:46 UTC, KonradKuznicki commented on server/api_handler_notifications.go
> +	al.writeJSONResponse(writer, http.StatusNotFound, nil)
done

2023-06-29 21:46 UTC, KonradKuznicki commented on server/notifications/channels/logger/logger.go
> +package logger
done

2023-06-29 21:47 UTC, KonradKuznicki commented on server/notifications/channels/rmailer/received_mail.go
> +type ReceivedMail struct {
to make it possible to use in tests in different package I had to make it outside of test package

2023-06-29 21:48 UTC, KonradKuznicki commented on server/api_listener.go
> +	runner := notifications.NewProcessor(notificationsLogger, store, notificationConsumers...)
done

2023-06-29 21:49 UTC, KonradKuznicki commented on server/notifications/channels/scriptRunner/consumer.go
> +	cancelFunc()
done

2023-06-29 21:50 UTC, KonradKuznicki commented on server/notifications/factory.go
> +func NewDispatcher(repository store) dispatcher {
done

2023-06-29 21:50 UTC, KonradKuznicki commented on server/notifications/factory.go
> +func (f dispatcher) Dispatch(ctx context.Context, origin refs.Origin, notification NotificationData) (refs.Identifiable, error) {
done

2023-06-29 21:50 UTC, KonradKuznicki commented on server/notifications/factory.go
> +		ID:     refs.GenerateIdentifiable(NotificationType),
done

2023-06-29 21:52 UTC, KonradKuznicki commented on server/notifications/factory.go
> +func FigureOutTarget(target string) Target {
would be nice, unfortunately it  makes some assumptions because target may be "smtp" or script path and Get sounds like it's obvious process almost like type casting

2023-06-29 21:53 UTC, KonradKuznicki commented on server/notifications/channels/scriptRunner/consumer.go
> +type ScriptIO struct {
done

2023-06-29 21:54 UTC, KonradKuznicki commented on server/notifications/repository/sqlite/repository.go
> +func (r repository) LogError(ctx context.Context, nid string, error string) error {
Actually they are - this table is actually more of a log then state storage

2023-06-29 21:55 UTC, KonradKuznicki commented on server/notifications/repository/sqlite/repository.go
> +		Origin:         string(details.Origin.Parent().Type()),
done

2023-06-29 21:56 UTC, KonradKuznicki commented on server/notifications/repository/inmemory/repository.go
> +package inmemory
done

2023-06-29 21:57 UTC, KonradKuznicki commented on server/notifications/repository/sqlite/bindata.go
> +// Code generated by go-bindata.
yes I wanted to make this module "modular" so I think that it should own all of it's internal stuff

2023-06-29 21:58 UTC, KonradKuznicki commented on server/notifications/repository/sqlite/migrations/001_init.up.sql
> +    origin VARCHAR(20) NOT NULL DEFAULT "",         -- origin, name of the subsystem that has created the notification
done

2023-06-29 21:59 UTC, KonradKuznicki commented on server/notifications/repository/sqlite/repository_test.go
> +var alertingIdentifiable = refs.GenerateIdentifiable("Alerting")
done

2023-06-29 22:01 UTC, KonradKuznicki commented on server/notifications/factory_test.go
> +func (suite *DispatcherTestSuite) TestDispatcherCreatesNotification() {
done

2023-06-29 22:01 UTC, KonradKuznicki commented on server/notifications/api.go
> +type REST interface {
done

2023-06-29 22:02 UTC, KonradKuznicki commented on server/notifications/api_test.go
> +package notifications
done

2023-06-29 22:02 UTC, KonradKuznicki commented on server/notifications/consumer_test.go
> +package notifications
done

2023-06-29 22:03 UTC, KonradKuznicki commented on server/notifications/runner.go
> +package notifications
done

2023-06-29 22:05 UTC, KonradKuznicki commented on server/notifications/runner_test.go
> +func (suite *ProcessorTestSuite) SendUnknown() notifications.NotificationDetails {
done

2023-06-30 01:02 UTC, morestatic commented on server/notifications/channels/rmailer/received_mail.go
> +type ReceivedMail struct {
i just meant to make the name clear that for testing (e.g. `ParseTestReceivedMail`) and maybe put in it's own package. otherwise i'm expecting use in the main code, cause there's nothing to indicate otherwise. at a minimum, i'd put a `// test only` comment. not urgent to fix but after the merge one of us should at least mark the fn.

2023-06-30 01:05 UTC, morestatic commented on server/notifications/repository/sqlite/bindata.go
> +// Code generated by go-bindata.
yes, i understand ... but the inconsistency isn't nice. better to create a ticket for a refactoring to move migrations to their relevant owner packages (for modularity) rather than make the decision on your own and then have one package that does things differently from all the other packages. so, in my mind, there isn't a good reason for this package to be different from everything else.

2023-06-30 01:10 UTC, morestatic commented on server/notifications/repository/sqlite/repository.go
> +func (r repository) LogError(ctx context.Context, nid string, error string) error {
the naming just looks too similar to writing to a regular log file, so it is confusing. also, what's the effect from the logical perspective. we calling a `setState` fn. that the underlying mechanism is a log shouldn't surface in the fn name. we'll need to rename but we can do after the merge.

2023-06-30 01:14 UTC, morestatic commented on server/notifications/factory.go
> +func FigureOutTarget(target string) Target {
figure out is still weird, and personally I think `Get` is just fine.

2023-06-30 02:38 UTC, morestatic approved these changes

2023-06-30 02:38 UTC, merged