Dev 2641
realvnc-labs/rport pull request #984
Opened 2023-03-28 08:39 UTC by edoardoc

2023-03-28 09:56 UTC, domenipavec commented on server/cgroups/group.go
> +					case "and":
What happens if the map has both `and` and `or`? Is that a documented behavior?

2023-03-28 09:58 UTC, domenipavec commented on server/clients/client_test.go
> +					// Tag: &cgroups.ParamValues{"Li nux", "Datacenter 2"},
I'm not sure about these comments. Is this something to be deleted or is it supposed to mean something?

2023-03-28 19:52 UTC, edoardoc commented on server/cgroups/group.go
> +		case map[string][]string:
I did some changes, now it should work

2023-03-28 19:53 UTC, edoardoc commented on server/cgroups/group.go
> +							matches++
changed the matches strategy into a map, also added some tests for this case

2023-03-28 19:54 UTC, edoardoc commented on server/cgroups/group.go
> +					case "and":
no, I will contact @thorstenkramm for this

2023-03-28 19:54 UTC, edoardoc commented on server/clients/client_test.go
> +					// Tag: &cgroups.ParamValues{"Li nux", "Datacenter 2"},
removed

2023-03-29 08:01 UTC, thorstenkramm commented on server/cgroups/group.go
> +					case "and":
@edoardoc @domenipavec 
Are you referring to an input like this?
```
"params": {
   "tags": {"and" : ["A", "B"], "or": ["C","D"] }
}
```
This must be denied. If the length of the array exceeds 1, we must exit with an error.

2023-03-29 09:03 UTC, edoardoc commented on server/cgroups/group.go
> +					case "and":
@thorstenkramm 
the right input would be:

```
"params": {
    "tag": [ { "and": ["T*", "Datacenter 2", "Datacenter 5"] } ]
}

```
tag is an array of strings (old specs) or an array of maps (new specs)
I am adding a test case in the [testfile](https://github.com/realvnc-labs/rport/blob/046efe305e08397039a5cb8999070c5a3ad09518/server/clients/client_test.go#L302) to address the situation

2023-03-29 13:46 UTC, domenipavec commented on server/clients/client_test.go
> +	var andTestCaseTrue cgroups.ClientParams
This is a bit weird way to write test cases, I would just put json in the  test cases struct and unmarshal in the loop.

2023-03-31 10:21 UTC, domenipavec commented on server/cgroups/group.go
> +			// unmarshaling as [ "first", "second"] failed
I think you should split the parsing in a separate fanction, that can then be used for validation when `Params` are submitted through the api and this error reported to the user.

2023-03-31 14:05 UTC, edoardoc commented on server/clients/client_test.go
> +	var andTestCaseTrue cgroups.ClientParams
changed

2023-03-31 14:07 UTC, edoardoc commented on server/cgroups/group.go
> +					case "and":
now it works with

```
"params": {
    "tags": { "and": ["T*", "Datacenter 2", "Datacenter 5"] }
}
```

and 
```

"params": {
    "tags": [ "T*", "Datacenter 2", "Datacenter 5" ]
}
```

2023-03-31 15:40 UTC, domenipavec requested changes

2023-03-31 15:40 UTC, domenipavec commented on server/api_handler_clientgroups.go
> +		var curGenericParam map[string][]string
This parsing is mostly the same as in the `MatchesRawTags`, you should extract the parsing into one function and use it in both places, otherwise it's dangerous that it will get out of sync with further changes.

2023-03-31 15:40 UTC, domenipavec commented on server/api_handler_clientgroups.go
> +			operator := strings.ToLower(reflect.ValueOf(curGenericParam).MapKeys()[0].String())
What happens if there are no map keys, probably panic? You have a check for this in the code below but not here. Exactly the reason I think this should just be merged into one function.
Also I think Thorsten wanted an error if both `and` and `or` are present.

2023-03-31 15:40 UTC, domenipavec commented on server/cgroups/group.go
> +		return false
This is a bit weird, I would expect an always match with no values (same as on line 110).

2023-03-31 15:40 UTC, domenipavec commented on server/clients/client_test.go
> -		{
Why are these test cases removed, shouldn't you just replace tag with `dataEmpty`?

2023-04-03 14:34 UTC, edoardoc commented on server/clients/client_test.go
> -		{
<img width="606" alt="image" src="https://user-images.githubusercontent.com/368717/229539139-3b3e36ad-16f9-4acc-be85-a4f897251a7c.png">

I think these are both wrong:

- the first one, "group with no tags, client with nil tags" gives a match for Tag = empty when data.tags == nil 

- the second one, "group with no tags, client with no tags" gives a match for Tag = empty when data.tags is empty

I believe the best outcome would be to give an error when Tag = empty or nil and then compare only non empty tags.

2023-04-03 18:38 UTC, domenipavec commented on server/cgroups/group.go
> +	operator := "or" // default
Nit.: I think operator strings should be defined as constants.

2023-04-03 18:38 UTC, domenipavec commented on server/clients/client_test.go
> -		{
There are a few cases of client param tags that I think we should cover, what client tags are shouldn't matter for these cases:

- When `tag` key is not present in `params`. This should be `true` and I think in this case `*json.RawMessage` is nil and it's covered by one of the test cases.
- When `"tag"=null`. I think this is the same as above, but maybe in this case `json.RawMessage = "null"`, and it won't parse correctly?
- When `"tag"=[]` or `"tag"={"or":[]}`. The behavior of `MatchesOneOf` for this is to always return `true`. I think we should match this behavior to be consistent.
- When `"tag"={"and":[]}`. I think this should be the same as for `or`, but it could be argued that it could also always be `false`. I think I would leave it up to Thorsten.

2023-04-04 07:44 UTC, edoardoc commented on server/clients/client_test.go
> -		{
for `tag = null` there is "group with unset tags, client with tags"
for `tag = []` or `tag = { anything }` indeed `MatchesOneOf` returns true, - erroneously: why there should be a match if there is no tags coming in? the same goes for `and`.
All these conditions should be caught and tested by `validateInputClientGroup` (checking the error condition of `ParseTag`) but you are right, it seems there is no validation for whatever goes in `MatchesOneOf`, neither are error messages produced...

2023-04-04 17:41 UTC, domenipavec commented on server/clients/client_test.go
> -		{
I'll approve for now, the behavior of these corner cases is up to Thorsten, we can also change it later if required.

2023-04-04 17:41 UTC, domenipavec approved these changes

2023-04-05 08:32 UTC, merged